services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: rag-backend
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:root@host.docker.internal:5432/rag_db
      - ELASTIC_URL=http://host.docker.internal:9200
      - CELERY_BROKER_URL=redis://host.docker.internal:6379/0
      - CELERY_RESULT_BACKEND=redis://host.docker.internal:6379/1
    ports:
      - "8000:8000"
    volumes:
      - backend_uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  backend_uploads:
