services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      network: host
    container_name: rag-frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000
    ports:
      - "3000:3000"
